export const WIDOCZNE_MENU = 'WIDOCZNE_MENU';
export const USTAW_WIDOCZNOŚĆ_MENU = 'USTAW_WIDOCZNOŚĆ_MENU';
export const ZMIEŃ_WERSJĘ_JĘZYKOWĄ = 'ZMIEŃ_WERSJĘ_JĘZYKOWĄ';
export const USTAW_WIDOCZNY_PRZYCISK = 'USTAW_WIDOCZNY_PRZYCISK';
export const USTAW_EDYTOWANY_ELEMENT = 'USTAW_EDYTOWANY_ELEMENT';
export const AKTUALIZUJ_LISTĘ_TESTÓW = 'AKTUALIZUJ_LISTĘ_TESTÓW';
export const ROZWIŃ_TEST = 'ROZWIŃ_TEST';
export const ROZWIŃ_ZAKŁADKĘ = 'ROZWIŃ_ZAKŁADKĘ';

export default {
    WIDOCZNE_MENU,
    USTAW_WIDOCZNOŚĆ_MENU,
    ZMIEŃ_WERSJĘ_JĘZYKOWĄ,
    USTAW_WIDOCZNY_PRZYCISK,
    USTAW_EDYTOWANY_ELEMENT,
    AKTUALIZUJ_LISTĘ_TESTÓW,
    ROZWIŃ_TEST,
    ROZWIŃ_ZAKŁADKĘ
}
