export const WIDOCZNE_MENU = 'WIDOCZNE_MENU';
export const USTAW_WIDOCZNOŚĆ_MENU = 'USTAW_WIDOCZNOŚĆ_MENU';
export const ZMIEŃ_WERSJĘ_JĘZYKOWĄ = 'ZMIEŃ_WERSJĘ_JĘZYKOWĄ';
export const USTAW_WIDOCZNY_PRZYCISK = 'USTAW_WIDOCZNY_PRZYCISK';
export const USTAW_EDYTOWANY_ELEMENT = 'USTAW_EDYTOWANY_ELEMENT';

export default {
    WIDOCZNE_MENU,
    USTAW_WIDOCZNOŚĆ_MENU,
    ZMIEŃ_WERSJĘ_JĘZYKOWĄ,
    USTAW_WIDOCZNY_PRZYCISK,
    USTAW_EDYTOWANY_ELEMENT
}
